#The game mode. Can be one of the following:
#FFA - Default mode, free combat.
#TDM - Basic team mode. The team that reaches a given amount of kills first wins.
mode: FFA

#Database configurations
database:
  address: 127.0.0.1
  port: 3306
  database: creepersmc
  username: root
  password: password